version: '3'
services: 
  dotnetcal:
    build: DotnetCalAPI/
    ports:
    - "5000:80"    
    environment:
      ASPNETCORE_URLS: "http://+"      
      ASPNETCORE_ENVIRONMENT: Development      
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ./DotnetCalAPI/https:/https/:ro